### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by wandohkesson** [wandohkesson/Huddle-Landing-Page1#1]
Hello Kofi,

Kindly work on the footer design for the landing page. Please create a new branch called Dev for all changes to the site. I will review this later and merge it with the main branch. Thank you.

**Comment by kaynert** [comment]
> Hello Kofi,
> 
> Kindly work on the footer design for the landing page. Please create a new branch called Dev for all changes to the site. I will review this later and merge it with the main branch. Thank you.

Hello Benjamin,

I have created the branch as requested and added the footer. Kindly review and revert. Thank you.
